version: '3.8'
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - restapi_network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: dijkstra
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - restapi_network

  panel:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - restapi_network


volumes:
  pg-data:

networks:
  restapi_network:
